[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npx serve -s dist"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[deploy.ingress]]
type = "web"
path = "/"
force_https = true 