[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[deploy.ingress]]
type = "web"
path = "/"

[[deploy.ingress]]
type = "tcp"
path = "/socket.io"
port = "3000"
internal_port = "3000"
force_https = true 